package:
  name: vtk
  version: 7.0.0

source:
  git_rev: tags/v7.0.0
  # git_url: https://gitlab.kitware.com/vtk/vtk.git
  git_url: /home/devuser/git-local/vtk

requirements:
  build:
    - cmake
    - python
    - pyqt
  run:
    - python
    - pyqt

build:
  number: 0

about:
  home: http://www.vtk.org/
  license: BSD
  summary: VTK is an open-source, freely available software system for 3D computer graphics. This conda package builds VTK against Python 3.5 and Qt4.